<a href="https://colab.research.google.com/github/YasminGarcia1210/SEMINARIO-PROFES-/blob/main/CUADERNO_2_SEMI_PROFES._.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src=http://www.acofi.edu.co/eiei2016/wp-content/uploads/2016/09/Logo-Universidad-ICESI.jpg width="200" height="200" align="center">

#Universidad Icesi
##Seminario Profes
###Cuaderno 2



# Vamos a continuar con los tipos de datos y asiganción en la Variables

#Agrupaciones

* Las listas son secuencias mutables de valores. MUTABLE: Qué puedo modificar en la lista.

>>lista=[1,2,3,4,5]

* Las tuplas son secuencias inmutables de valores. TUPLA: No se modifican (cedula)

>>tupla=(1,2,3,4,5)

* Los conjuntos se utilizan para representar conjuntos únicos de elementos, es decir, en un conjunto no pueden existir dos objetos iguales. CONJUNTO: Una lista dentro de otra. (elementos diferentes)

>> conjunto=set([1,2,3,4])

* Los diccionarios son tipos especiales de contenedores en los que se puede acceder a sus elementos a partir de una clave única. (Representar la palabra con una letra). eje: a= Marin. (definir variables)

>> dicionario= {'a':"Marin", 'b':"Lopez", 'c':1 }

# Libreria 👀

# Vamos a mencionar como funciona la libreria Numpy



#Libreria Numpy

NumPy es una librería de Python especializada en el cálculo numérico y el análisis de datos, especialmente para un gran volumen de datos.

* [Curiosidades de Numpy](https://aprendeconalf.es/docencia/python/manual/numpy/)

```
Import Numpy as np
```

**Sintaxis**

```
np.sqrt(x)
```

# Usando Numpy vamos a introducir el concepto de arreglo (vectores)

##Arreglos #

Un **array** en Python es un tipo de variable especial que puede alojar dentro de sí varios valores al mismo tiempo.

Es decir, no es que se alojen los datos en un mismo lugar al mismo tiempo, sino que se tienen una serie de contenedores que conforman el array y en cada uno de esos contenedores se guardan datos distintos

##Diferencias entre listas y arreglos

Las listas y los arrays se comportan de manera similar y ambos son una secuencia ordenada de elementos. También son mutables (CAMBIAN) y no poseen tamaños fijos, lo que quiere decir que pueden crecer y reducirse a lo largo del uso del programa.

Todos los elementos de una lista y un array en Python pueden agregarse y eliminarse. Esto los convierte en objetos muy flexibles y fáciles de trabajar.

Una de las grandes diferencias es que, **a diferencia de los arrays (arreglos), las listas pueden almacenar diversos tipos de datos.**

In [ ]:
#creando un array (arreglo)
import numpy as np

In [ ]:
np.array([0,100]) #Asi se escribe un arreglo ...>Sirve para guardar vectores

array([  0, 100])

In [ ]:
arreglo=[1,2,3] #Vector

arreglo_anidado=[[1,2,3],[2,3,4],[5,6,7]] #Esto es una Matriz

In [ ]:
np.array([1, 2, 3], dtype=complex) #CONVERTIR A UN COMPLEJO


array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
ma=[[1., 2., 3.], [1,2,3], [1+1.j, 2+2.j, 5.j]]
ma

[[1.0, 2.0, 3.0], [1, 2, 3], [(1+1j), (2+2j), 5j]]

In [ ]:
#Convertir una lista en un arreglo

lista=[1,2,3,4]
print(lista)
np.array(lista)

[1, 2, 3, 4]


array([1, 2, 3, 4])

In [ ]:
#Función Range (np.arange(p_1, p_2, n))             ------> HACER RANGO DE # DE 0 A 10

#np.arange (0,10) #Todos los numeros entre 0 y 9

np.arange(0,101,2)#-------->#HACER RANGO DE # DE 0-100 DE (2 en 2) cuenta de 2 en 2

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [ ]:
##Ceros y unos en el vector: genera arreglos de ceros y unos
#np.zeros(3)
np.ones(9) #  ------------------> AGREGAR 9 UNOS

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# ceros y unos en la matriz

np.zeros((4,6)) # 4 filas y 6 columnas

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.identity(3) #Matriz identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
Vector=np.array([1,1,1])
Mat=np.diag(Vector)
print(Mat)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
A=[[1,2,3], [5,6,7],[4,5,6]]
A

[[1, 2, 3], [5, 6, 7], [4, 5, 6]]

In [ ]:
np.dot(A,Mat)

array([[1, 2, 3],
       [5, 6, 7],
       [4, 5, 6]])

# Función Linspace   -----> para GRAFICAS (Sirve para la simetria de los puntos)

NumPy tiene el método linspace que genera puntos uniformemente espaciados entre dos números.

##Sintaxis

```
np.linspace(a,b,n)   -----> Forma escribir

a=
b=
n= Es la cantidad de datos
```
>Por defecto, linspace genera 50 valores entre a y b


In [ ]:
np.linspace(0,10,100) #----------> Escribe numeros desde 0 hasta 10

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [ ]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

# FUNCIÓN IF,ELSE ELIF

Las funciones condicionales funciones para toma de decisiones,es un ciclo Booleano iterativo

### Sintaxis


```
if condicion1:
  return acción 1

else condicion2:
  return acción2

elif:
  retunr acción final
```



In [ ]:
x=5

In [ ]:
#Función a trozos

if x>0:
  return x*2
elif:
  return 0

#Ciclos for
El bucle **for** se utiliza para recorrer los elementos de un objeto iterable (lista, tupla, conjunto, diccionario, …) y ejecutar un bloque de código.

En cada paso de la iteración se tiene en cuenta a un único elemento del objeto iterable, sobre el cuál se pueden aplicar una serie de operaciones.

In [ ]:
lista=[1,2,3,4,5]

for x in lista:
  print(x**2)

1
4
9
16
25


In [ ]:
#Número en rango
for x in range(0,10): #(Pide que me de numero de 0 a 9)
  print(x-5)

In [ ]:
#Ejemplo. Crear una lista con los números del 0 al 10 llamado L1 y luego hacer una lista con los números elevados al cuadrado llamado L2

l1=[x for x in range(0,10)]
print(l1)

l2=[y**2 for y in l1]
l2

# Graficas

Para Graficar vamos a importar la libreria Matplotlib de Python

```
import matplotlib.pyplot as plt
```

Revise las caracteristicas de la Libreria Matplotlib [Libreria_Matplotlib](https://matplotlib.org/)

* [Consejos para Matplotlib](https://github.com/YasminGarcia1210/MAT_APLICADAS03/blob/main/CUADERNO_3_GRAFICAS.ipynb)
